# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
